# Generated by Django 5.1.2 on 2024-10-25 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('recompensas', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDestinatario', models.EmailField(max_length=254, unique=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceito', 'Aceito'), ('Expirado', 'Expirado')], default='Pendente', max_length=50)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('userRemetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='member_get_member.member')),
            ],
        ),
    ]
