# Generated by Django 5.1.3 on 2024-11-07 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('userDestinatario', models.EmailField(max_length=254, unique=True)),
                ('link', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceito', 'Aceito'), ('Expirado', 'Expirado')], default='Pendente', max_length=50)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('recompensas', models.IntegerField(default=0)),
                ('convites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_convidados', to='member_get_member.convite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='convite',
            name='userRemetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to='member_get_member.member'),
        ),
    ]
