# Generated by Django 5.1.2 on 2024-11-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_get_member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='qtd_convites',
        ),
    ]
