# Generated by Django 5.1.2 on 2024-10-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_get_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDestinatario', models.EmailField(max_length=254, unique=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceito', 'Aceito'), ('Expirado', 'Expirado')], default='Pendente', max_length=50)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('userRemetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='member_get_member.member')),
            ],
        ),
    ]
