# Generated by Django 5.1.2 on 2024-10-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_get_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='convites',
            field=models.ManyToManyField(blank=True, related_name='membros_convidados', to='member_get_member.convite'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='userRemetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to='member_get_member.member'),
        ),
    ]
