# Generated by Django 5.1.3 on 2024-11-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_get_member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nome',
        ),
    ]
