# Generated by Django 5.1.2 on 2024-10-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_get_member', '0002_member_convites_alter_convite_userremetente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='id',
        ),
        migrations.AlterField(
            model_name='convite',
            name='link',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
