# Generated by Django 5.1.2 on 2024-11-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_get_member', '0002_remove_member_qtd_convites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='convites',
        ),
    ]
