# Generated by Django 5.1.3 on 2024-11-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_get_member', '0002_remove_member_email_remove_member_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Comentários gerais', 'Comentários gerais'), ('Sugestões de melhoria', 'Sugestões de melhoria'), ('Problemas tecnicos', 'Problemas tecnicos')], default='Comentários gerais', max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='member_get_member.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_feedbacks', to='member_get_member.feedback'),
        ),
    ]
