# Generated by Django 5.1.3 on 2024-11-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_get_member', '0003_feedback_member_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='convites',
        ),
        migrations.RemoveField(
            model_name='member',
            name='feedbacks',
        ),
    ]
