@startuml casodeuso
left to right direction

actor "Visitante" as Visitante
actor "Usuário" as Usuario
actor "Administrador" as Administrador
actor "Editora" as Editora

usecase "Cadastrar Usuário" as CU01
usecase "Fazer Login" as CU02
usecase "Pesquisar Audiobook" as CU03
usecase "Ouvir Audiobook" as CU04
usecase "Personalizar Sons Relaxantes" as CU05
usecase "Gerenciar Playlists" as CU06
usecase "Avaliar e Comentar Audiobook" as CU07
usecase "Gerenciar Perfil de Usuário" as CU08
usecase "Receber Recomendações Personalizadas" as CU09
usecase "Ver Histórico de Audiobooks Ouvidos" as CU10
usecase "Favoritar Audiobook" as CU11
usecase "Fazer Download de Audiobook (Offline)" as CU12
usecase "Assinar Plano Premium" as CU13

usecase "Gerenciar Usuários" as CU14
usecase "Gerenciar Audiobooks" as CU15
usecase "Gerenciar Planos de Assinatura" as CU16
usecase "Gerar Relatórios de Uso" as CU17

usecase "Cadastrar Audiobooks" as CU18
usecase "Gerenciar Audiobooks Editora" as CU19
usecase "Acompanhar Estatísticas de Audiobooks" as CU20

Visitante --> CU01

Usuario --> CU02
Usuario --> CU03
Usuario --> CU04
Usuario --> CU05
Usuario --> CU06
Usuario --> CU07
Usuario --> CU08
Usuario --> CU09
Usuario --> CU10
Usuario --> CU11
Usuario --> CU12
Usuario --> CU13

Administrador --> CU14
Administrador --> CU15
Administrador --> CU16
Administrador --> CU17

Editora --> CU18
Editora --> CU19
Editora --> CU20

@enduml
