# Generated by Django 5.1.2 on 2024-11-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IQuiriumApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nome',
        ),
    ]
