@startuml casodeuso
left to right direction

actor "Usuário Autenticado" as UsuarioAutenticado
actor "Sistema" as Sistema
actor "Admin/Equipe de Análise" as AdminEquipeAnalise

usecase "Gerar Link de Convite" as CU01
usecase "Compartilhar Link de Convite" as CU02
usecase "Registrar via Link de Convite" as CU03
usecase "Validar Link de Convite" as CU04
usecase "Enviar Feedback" as CU05
usecase "Listar Feedbacks" as CU06
usecase "Classificar Feedback" as CU07
usecase "Analisar Feedback" as CU08

UsuarioAutenticado --> CU01
UsuarioAutenticado --> CU02
Sistema --> CU03
Sistema --> CU04
UsuarioAutenticado --> CU05
AdminEquipeAnalise --> CU06
AdminEquipeAnalise --> CU07
AdminEquipeAnalise --> CU08

@enduml