# Generated by Django 5.1.2 on 2024-11-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='feedbacks',
        ),
    ]
