# Generated by Django 5.1.2 on 2024-10-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_member', '0002_member_feedbacks_alter_feedback_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tipo',
            field=models.CharField(choices=[('Comentários gerais', 'Comentários gerais'), ('Sugestões de melhoria', 'Sugestões de melhoria'), ('Problemas tecnicos', 'Problemas tecnicos')], default='Comentários gerais', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_feedbacks', to='feedback_member.feedback'),
        ),
    ]
